lessons:
  outputs:
    dev:
      dataset: dbt_derek
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: quick-dimension-404720
      threads: 60
      type: bigquery
  target: dev
